"""update models add issuing_authority

Revision ID: 0848723c4c42
Revises: 45e64e3c04f1
Create Date: 2024-05-20 17:54:57.699710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0848723c4c42'
down_revision = '45e64e3c04f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('issuing_authority', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_issuing_authority'), 'items', ['issuing_authority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_issuing_authority'), table_name='items')
    op.drop_column('items', 'issuing_authority')
    # ### end Alembic commands ###
