"""edit models User roles JSON

Revision ID: 0e7532002cd1
Revises: 782b4c5d8b13
Create Date: 2024-05-06 11:22:03.071953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7532002cd1'
down_revision = '782b4c5d8b13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
