"""edit models User UUID

Revision ID: 1395fe1575ac
Revises: 0e7532002cd1
Create Date: 2024-05-06 14:59:25.513989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1395fe1575ac'
down_revision = '0e7532002cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
