"""Добавлена таблицы UP:35

Revision ID: 40a0f60a0696
Revises: 7f36881bad6a
Create Date: 2024-09-15 23:39:09.470244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a0f60a0696'
down_revision = '7f36881bad6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('receiver_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'receiver_id')
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###
