"""first update

Revision ID: 45e64e3c04f1
Revises: 
Create Date: 2024-05-20 14:54:41.821248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e64e3c04f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('quantitys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantitys_id'), 'quantitys', ['id'], unique=False)
    op.create_index(op.f('ix_quantitys_name'), 'quantitys', ['name'], unique=True)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_register', sa.String(), nullable=True),
    sa.Column('name_entity', sa.String(), nullable=True),
    sa.Column('tax_name', sa.String(), nullable=True),
    sa.Column('entity_address', sa.String(), nullable=True),
    sa.Column('address_program', sa.String(), nullable=True),
    sa.Column('cipher', sa.String(), nullable=True),
    sa.Column('title_school', sa.String(), nullable=True),
    sa.Column('quantity_school', sa.String(), nullable=True),
    sa.Column('forms_education', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('issuing_license', sa.String(), nullable=True),
    sa.Column('data_license', sa.String(), nullable=True),
    sa.Column('form_number', sa.String(), nullable=True),
    sa.Column('form_number_suspended', sa.String(), nullable=True),
    sa.Column('form_number_start', sa.String(), nullable=True),
    sa.Column('form_number_stop', sa.String(), nullable=True),
    sa.Column('data_address', sa.String(), nullable=True),
    sa.Column('form_number_data', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('quantity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quantity_id'], ['quantitys.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_address_program'), 'items', ['address_program'], unique=False)
    op.create_index(op.f('ix_items_cipher'), 'items', ['cipher'], unique=False)
    op.create_index(op.f('ix_items_contract_number'), 'items', ['contract_number'], unique=False)
    op.create_index(op.f('ix_items_data_address'), 'items', ['data_address'], unique=False)
    op.create_index(op.f('ix_items_data_license'), 'items', ['data_license'], unique=False)
    op.create_index(op.f('ix_items_entity_address'), 'items', ['entity_address'], unique=False)
    op.create_index(op.f('ix_items_form_number'), 'items', ['form_number'], unique=False)
    op.create_index(op.f('ix_items_form_number_data'), 'items', ['form_number_data'], unique=False)
    op.create_index(op.f('ix_items_form_number_start'), 'items', ['form_number_start'], unique=False)
    op.create_index(op.f('ix_items_form_number_stop'), 'items', ['form_number_stop'], unique=False)
    op.create_index(op.f('ix_items_form_number_suspended'), 'items', ['form_number_suspended'], unique=False)
    op.create_index(op.f('ix_items_forms_education'), 'items', ['forms_education'], unique=False)
    op.create_index(op.f('ix_items_full_name'), 'items', ['full_name'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_issuing_license'), 'items', ['issuing_license'], unique=False)
    op.create_index(op.f('ix_items_name_entity'), 'items', ['name_entity'], unique=False)
    op.create_index(op.f('ix_items_number_register'), 'items', ['number_register'], unique=False)
    op.create_index(op.f('ix_items_quantity_school'), 'items', ['quantity_school'], unique=False)
    op.create_index(op.f('ix_items_tax_name'), 'items', ['tax_name'], unique=False)
    op.create_index(op.f('ix_items_title_school'), 'items', ['title_school'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_items_title_school'), table_name='items')
    op.drop_index(op.f('ix_items_tax_name'), table_name='items')
    op.drop_index(op.f('ix_items_quantity_school'), table_name='items')
    op.drop_index(op.f('ix_items_number_register'), table_name='items')
    op.drop_index(op.f('ix_items_name_entity'), table_name='items')
    op.drop_index(op.f('ix_items_issuing_license'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_full_name'), table_name='items')
    op.drop_index(op.f('ix_items_forms_education'), table_name='items')
    op.drop_index(op.f('ix_items_form_number_suspended'), table_name='items')
    op.drop_index(op.f('ix_items_form_number_stop'), table_name='items')
    op.drop_index(op.f('ix_items_form_number_start'), table_name='items')
    op.drop_index(op.f('ix_items_form_number_data'), table_name='items')
    op.drop_index(op.f('ix_items_form_number'), table_name='items')
    op.drop_index(op.f('ix_items_entity_address'), table_name='items')
    op.drop_index(op.f('ix_items_data_license'), table_name='items')
    op.drop_index(op.f('ix_items_data_address'), table_name='items')
    op.drop_index(op.f('ix_items_contract_number'), table_name='items')
    op.drop_index(op.f('ix_items_cipher'), table_name='items')
    op.drop_index(op.f('ix_items_address_program'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_quantitys_name'), table_name='quantitys')
    op.drop_index(op.f('ix_quantitys_id'), table_name='quantitys')
    op.drop_table('quantitys')
    op.drop_table('users')
    # ### end Alembic commands ###
