"""Добавлена таблицы  UP:29

Revision ID: 77599ac612f2
Revises: c3d9e7c8d3ec
Create Date: 2024-08-19 16:07:34.782970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77599ac612f2'
down_revision = 'c3d9e7c8d3ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
