"""Добавлена таблицы UP:34

Revision ID: 7f36881bad6a
Revises: 92813e6c78ae
Create Date: 2024-09-15 23:21:55.954203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f36881bad6a'
down_revision = '92813e6c78ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
