"""add models is_active: bool

Revision ID: baa409e073b2
Revises: fdbc97caff63
Create Date: 2024-05-08 15:15:30.347334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa409e073b2'
down_revision = 'fdbc97caff63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('regions', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'is_active')
    op.drop_column('items', 'is_active')
    # ### end Alembic commands ###
