"""commit up:25

Revision ID: bbd5c4459cab
Revises: 0dc53105c9cc
Create Date: 2024-07-31 18:05:43.324716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd5c4459cab'
down_revision = '0dc53105c9cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_action_history', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_action_history', 'name')
    # ### end Alembic commands ###
