"""Добавлена таблицы  UP:28

Revision ID: c3d9e7c8d3ec
Revises: 4595acef6b14
Create Date: 2024-08-19 15:01:09.919472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d9e7c8d3ec'
down_revision = '4595acef6b14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
