"""edit models User UUID new

Revision ID: c941d686d68d
Revises: 1395fe1575ac
Create Date: 2024-05-06 15:19:27.467577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c941d686d68d'
down_revision = '1395fe1575ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
